### ISSUE TITLE
Iterating through the cache....

### ISSUE THREAD

**Issue by JRAndreassen** [moka-rs/moka-cht#5]
Hi...
What is the idiomatic way of iterating through the cache ?
There is no "iter()"/into_iter()" etc.
At least there should be  a "keys()" method so I can iterate through the values...
Or am I missing something ?

Thanks
  JR

**Comment by tatsuya6502** [comment]
Hi @JRAndreassen

Are you looking for `iter()` method in [moka](https://crates.io/crates/moka) cache? or [moka-cht](https://crates.io/crates/moka-cht) (concurrent hash table)?

If the former, which `Cache` are you trying to use? (`moka::sync`, `moka::future`, ...)
https://docs.rs/moka/latest/moka/#examples

As of moka cache v0.8.1, an experimental `moka::dash::Cache` has `iter()` method, but others do not.
https://docs.rs/moka/latest/moka/dash/struct.Cache.html#method.iter

**Comment by JRAndreassen** [comment]
Hi @tatsuya6502 ,
I have moved it to [moka](https://github.com/moka-rs/moka/issues/112)...
